// Command gen-rbac writes deploy/rbac.yaml. The deprecated-API list rules
// are derived from the embedded Pluto table so RBAC never drifts from it.
package main

import (
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/filidorwiese/kubegrade/internal/collect"
	"github.com/filidorwiese/kubegrade/internal/data"
)

const header = `# Generated by hack/gen-rbac; do not edit by hand.
# Read-only. secrets: the agent lists only owner=helm and kubernetes.io/tls
# secrets (label + field selector in code) and never logs their contents.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubegrade-agent
  namespace: kubegrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubegrade-agent
rules:
  - apiGroups: [""]
    resources: [nodes, pods, namespaces, persistentvolumeclaims, persistentvolumes, secrets]
    verbs: [get, list]
  - apiGroups: [""]
    resources: [nodes/proxy]
    verbs: [get]
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [get, list]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list]
  - apiGroups: [cert-manager.io]
    resources: [certificates]
    verbs: [get, list]
  # Deprecated API listing, one rule per group from Pluto's k8s rows.
`

const footer = `---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubegrade-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubegrade-agent
subjects:
  - kind: ServiceAccount
    name: kubegrade-agent
    namespace: kubegrade
`

func main() {
	out := "deploy/rbac.yaml"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	t, err := data.Embedded()
	if err != nil {
		log.Fatal(err)
	}
	groups := map[string]map[string]bool{}
	for _, d := range collect.K8sDeprecations(t) {
		group := ""
		if i := strings.Index(d.Version, "/"); i >= 0 {
			group = d.Version[:i]
		}
		if groups[group] == nil {
			groups[group] = map[string]bool{}
		}
		groups[group][plural(d.Kind)] = true
	}

	var b strings.Builder
	b.WriteString(header)
	for _, g := range sortedKeys(groups) {
		fmt.Fprintf(&b, "  - apiGroups: [%q]\n    resources: [%s]\n    verbs: [get, list]\n",
			g, strings.Join(sortedKeys(groups[g]), ", "))
	}
	b.WriteString(footer)
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("wrote", out)
}

// plural follows the k8s resource naming convention closely enough for the
// Pluto kinds; a wrong guess only shows up as a collector error.
func plural(kind string) string {
	k := strings.ToLower(kind)
	switch {
	case strings.HasSuffix(k, "s"):
		return k + "es"
	case strings.HasSuffix(k, "y"):
		return k[:len(k)-1] + "ies"
	}
	return k + "s"
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
